### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '0/1.png'

### ISSUE THREAD

**Issue by yurainHung** [CosiNull/minesweeperBot#4]
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\minesweeperBot-main\minesweeperBot-main\Minesweeper\play.py", line 4, in <module>
    from boardConverter import *
  File "C:\Users\USER\Downloads\minesweeperBot-main\minesweeperBot-main\Minesweeper\boardConverter.py", line 5, in <module>
    from cellColors import pixelCoordinate
  File "C:\Users\USER\Downloads\minesweeperBot-main\minesweeperBot-main\Minesweeper\cellColors.py", line 15, in <module>
    examinedImg = Image.open(code+"/1.png")
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PIL\Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '0/1.png'

**Comment by Nguyenwasd72** [comment]
did you delete all number'd folders

**Comment by onenok** [comment]
> Traceback (most recent call last): File "C:\Users\USER\Downloads\minesweeperBot-main\minesweeperBot-main\Minesweeper\play.py", line 4, in from boardConverter import * File "C:\Users\USER\Downloads\minesweeperBot-main\minesweeperBot-main\Minesweeper\boardConverter.py", line 5, in from cellColors import pixelCoordinate File "C:\Users\USER\Downloads\minesweeperBot-main\minesweeperBot-main\Minesweeper\cellColors.py", line 15, in examinedImg = Image.open(code+"/1.png") File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PIL\Image.py", line 2975, in open fp = builtins.open(filename, "rb") FileNotFoundError: [Errno 2] No such file or directory: '0/1.png'

just delete the bot file and redownload

**Comment by onenok** [comment]
u deleted file "0"
